name: 'hr_analytics'
version: '1.0.0'

profile: 'hr_analytics'

model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  hr_analytics:
    staging:
      +materialized: view
    core:
      +materialized: table
    mart:
      +materialized: table
